import { createAsyncThunk, createSlice, PayloadAction } from "@reduxjs/toolkit";
import $axios from "@/utils/axios";
import generateNonce from "@/utils/generateNonce";

export interface AuthState {
  nonce: string;
  address: string;
  token: string;
  status: "idle" | "loading" | "failed";
}

export interface GetTokenPayload {
  address: string;
  signature: any;
  nonce: string;
}

const initialState: AuthState = {
  nonce: generateNonce(),
  address: "",
  token: "",
  status: "idle",
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const getNonce = createAsyncThunk(
  "auth/getNonce",
  async (address: string) => {
    const response = await $axios.post("/auth/get-nonce", { address });
    return response.data;
  },
);

export const getToken = createAsyncThunk(
  "auth/getToken",
  async (payload: GetTokenPayload) => {
    const { address, signature, nonce } = payload;
    const response = await $axios.post("/auth/signin-with-phantom", {
      address,
      signature,
      nonce,
    });
    return response.data;
  },
);

export const authSlice = createSlice({
  name: "auth",
  initialState,
  reducers: {
    setAddress: (state, action: PayloadAction<string>) => {
      state.address = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getToken.pending, (state) => {
        state.status = "loading";
      })
      .addCase(getToken.fulfilled, (state, action) => {
        state.status = "idle";
        state.token += action.payload.token;
      });
  },
});

export const { setAddress } = authSlice.actions;

export default authSlice.reducer;
